name:                safeboard
version:             0.1.0.0
github:              "neclitoris/safeboard"
author:              "Nikita Solodovnikov"
maintainer:          "nas140301@gmail.com"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/neclitoris/safeboard#readme>

dependencies:
- base >= 4.7 && < 5
- parsec >= 3.1 && < 4
- vector >= 0.12 && < 1
- data-default >= 0.7 && < 1
- template-haskell >= 2.15 && < 3
- tasty >= 1.3 && < 2
- tasty-hunit >= 0.10 && < 1
- th-test-utils >= 1.1 && < 2

library:
  source-dirs: src
  exposed-modules:
    Quotes.Base64
    Quotes.Base16
    Quotes.DataURL
    Quotes.Slices
  other-modules:
    Data.Vector.Lift
    Text.Parsers.Base16
    Text.Parsers.Base64
    Text.Parsers.DataURL

tests:
  safeboard-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - safeboard
